version: "3.9"
services:
  web:
    build: .
    working_dir: /app
    ports:
     - "5000-5002:5000"
    volumes:
     - .:/app
    links:
     - db
    deploy:
      mode: replicated
      replicas: 3
  db:
    image: redis
    
